import {
  StyleSheet,
  Text,
  View,
  ScrollView,
  TouchableOpacity,
  ActivityIndicator,
  Share,
} from "react-native";
import React, { useEffect, useState } from "react";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { useRouter, useLocalSearchParams } from "expo-router";
import {
  getAnalysisById,
  AnalysisResponse,
  SurveySummary,
  Finding,
  Insight,
  Correlation,
} from "@/api/ai";
import { getSurveyById } from "@/api/surveys";

interface SurveyWithName extends SurveySummary {
  surveyTitle: string;
}

export default function AnalysisInsights() {
  const router = useRouter();
  const { analysisId } = useLocalSearchParams<{ analysisId: string }>();
  const [analysis, setAnalysis] = useState<AnalysisResponse | null>(null);
  const [surveysWithNames, setSurveysWithNames] = useState<SurveyWithName[]>(
    []
  );
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (analysisId) {
      loadAnalysis();
    }
  }, [analysisId]);

  const loadAnalysis = async () => {
    if (!analysisId) return;

    setLoading(true);
    setError(null);
    try {
      const data = await getAnalysisById(analysisId);
      setAnalysis(data);

      // Fetch survey names
      if (data.data?.surveys) {
        const surveysWithTitles = await Promise.all(
          data.data.surveys.map(async (survey) => {
            try {
              const surveyData = await getSurveyById(survey.surveyId);
              return {
                ...survey,
                surveyTitle: surveyData.title,
              };
            } catch (err) {
              console.error(`Error fetching survey ${survey.surveyId}:`, err);
              return {
                ...survey,
                surveyTitle: "Survey",
              };
            }
          })
        );
        setSurveysWithNames(surveysWithTitles);
      }
    } catch (err: any) {
      console.error("Error loading analysis:", err);
      setError(err.message || "Failed to load analysis");
    } finally {
      setLoading(false);
    }
  };

  const handleShare = async () => {
    if (!analysis || !analysis.data) return;

    try {
      let shareText = `Analysis Insights\n\nOverview:\n${analysis.data.overview}\n\n`;

      if (surveysWithNames.length > 0) {
        shareText += `Surveys Analyzed:\n`;
        surveysWithNames.forEach((survey) => {
          shareText += `- ${survey.surveyTitle} (${survey.responseCountUsed} responses)\n`;
        });
      }

      shareText += `\nGenerated by SIGHT`;

      await Share.share({
        message: shareText,
        title: "Survey Analysis",
      });
    } catch (err) {
      console.error("Error sharing:", err);
    }
  };

  if (loading) {
    return (
      <SafeAreaView style={styles.container}>
        <View style={styles.centerContainer}>
          <ActivityIndicator size="large" color="#8B5CF6" />
          <Text style={styles.loadingText}>Loading insights...</Text>
        </View>
      </SafeAreaView>
    );
  }

  if (error || !analysis || !analysis.data) {
    return (
      <SafeAreaView style={styles.container}>
        <View style={styles.centerContainer}>
          <Ionicons name="alert-circle-outline" size={48} color="#EF4444" />
          <Text style={styles.errorText}>
            {error || "Analysis data not available"}
          </Text>
          <TouchableOpacity onPress={() => router.back()} style={styles.button}>
            <Text style={styles.buttonText}>Go Back</Text>
          </TouchableOpacity>
        </View>
      </SafeAreaView>
    );
  }

  const totalResponses = surveysWithNames.reduce(
    (sum, s) => sum + (s.responseCountUsed || 0),
    0
  );

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        {/* Header */}
        <View style={styles.header}>
          <TouchableOpacity
            onPress={() => router.back()}
            style={styles.backButton}
          >
            <Ionicons name="arrow-back" size={24} color="#111827" />
          </TouchableOpacity>
          <View style={styles.headerTextContainer}>
            <Text style={styles.title}>Analysis Insights</Text>
            <Text style={styles.subtitle}>
              {new Date(analysis.createdAt || "").toLocaleDateString("en-US", {
                year: "numeric",
                month: "long",
                day: "numeric",
              })}
            </Text>
          </View>
          <TouchableOpacity onPress={handleShare} style={styles.shareButton}>
            <Ionicons name="share-outline" size={24} color="#8B5CF6" />
          </TouchableOpacity>
        </View>

        {/* Success Badge */}
        <View style={styles.successBadge}>
          <Ionicons name="checkmark-circle" size={24} color="#10B981" />
          <Text style={styles.successText}>Analysis Complete</Text>
        </View>

        {/* Stats Cards */}
        <View style={styles.statsGrid}>
          <StatCard
            icon="document-text"
            label="Surveys"
            value={surveysWithNames.length}
            color="#3B82F6"
          />
          <StatCard
            icon="people"
            label="Responses"
            value={totalResponses}
            color="#10B981"
          />
        </View>

        {/* Data Quality */}
        {analysis.data.dataQualityNotes && (
          <View style={styles.qualityCard}>
            <View style={styles.cardHeader}>
              <Ionicons name="shield-checkmark" size={24} color="#10B981" />
              <Text style={styles.cardTitle}>Data Quality</Text>
            </View>
            <View style={styles.confidenceRow}>
              <Text style={styles.confidenceLabel}>Confidence Score:</Text>
              <View style={styles.confidenceBadge}>
                <Text style={styles.confidenceValue}>
                  {Math.round(
                    analysis.data.dataQualityNotes.confidenceScore * 100
                  )}
                  %
                </Text>
              </View>
            </View>
            <Text style={styles.qualityText}>
              {analysis.data.dataQualityNotes.confidenceExplanation}
            </Text>
            {analysis.data.dataQualityNotes.notes &&
              analysis.data.dataQualityNotes.notes.length > 0 && (
                <View style={styles.notesSection}>
                  {analysis.data.dataQualityNotes.notes.map((note, index) => (
                    <View key={index} style={styles.noteItem}>
                      <Ionicons
                        name="information-circle"
                        size={16}
                        color="#6B7280"
                      />
                      <Text style={styles.noteText}>{note}</Text>
                    </View>
                  ))}
                </View>
              )}
          </View>
        )}

        {/* Overview Card */}
        <View style={styles.overviewCard}>
          <View style={styles.cardHeader}>
            <Ionicons name="document-text-outline" size={24} color="#8B5CF6" />
            <Text style={styles.cardTitle}>Overview</Text>
          </View>
          <Text style={styles.overviewText}>{analysis.data.overview}</Text>
        </View>

        {/* Survey Insights */}
        {surveysWithNames && surveysWithNames.length > 0 && (
          <View style={styles.surveysSection}>
            <Text style={styles.sectionTitle}>Survey Details</Text>
            {surveysWithNames.map((survey, index) => (
              <SurveyInsightCard key={index} survey={survey} />
            ))}
          </View>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

interface SurveyInsightCardProps {
  survey: SurveyWithName;
}

const SurveyInsightCard: React.FC<SurveyInsightCardProps> = ({ survey }) => {
  return (
    <View style={styles.surveyCard}>
      {/* Survey Header */}
      <View style={styles.surveyHeader}>
        <Text style={styles.surveyTitle}>{survey.surveyTitle}</Text>
        <View style={styles.responseBadge}>
          <Ionicons name="people" size={16} color="#8B5CF6" />
          <Text style={styles.responseText}>
            {survey.responseCountUsed} responses
          </Text>
        </View>
      </View>

      {/* Findings */}
      {survey.findings && survey.findings.length > 0 && (
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Ionicons name="bulb" size={20} color="#F59E0B" />
            <Text style={styles.sectionHeaderText}>Key Findings</Text>
          </View>
          {survey.findings.map((finding: Finding, index: number) => (
            <View key={index} style={styles.findingCard}>
              <Text style={styles.findingTitle}>{finding.title}</Text>
              <Text style={styles.findingDescription}>
                {finding.description}
              </Text>
            </View>
          ))}
        </View>
      )}

      {/* Insights */}
      {survey.insights && survey.insights.length > 0 && (
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Ionicons name="sparkles" size={20} color="#8B5CF6" />
            <Text style={styles.sectionHeaderText}>Insights</Text>
          </View>
          {survey.insights.map((insight: Insight, index: number) => (
            <View key={index} style={styles.insightCard}>
              <View style={styles.themeChip}>
                <Text style={styles.themeText}>{insight.theme}</Text>
              </View>
              <Text style={styles.insightTitle}>{insight.title}</Text>
              <Text style={styles.insightDescription}>
                {insight.description}
              </Text>
              {insight.examples && insight.examples.length > 0 && (
                <View style={styles.examplesSection}>
                  <Text style={styles.examplesLabel}>Examples:</Text>
                  {insight.examples.map((example, idx) => (
                    <View key={idx} style={styles.exampleItem}>
                      <Text style={styles.exampleBullet}>•</Text>
                      <Text style={styles.exampleText}>{example}</Text>
                    </View>
                  ))}
                </View>
              )}
            </View>
          ))}
        </View>
      )}

      {/* Correlations */}
      {survey.correlations && survey.correlations.length > 0 && (
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Ionicons name="git-compare" size={20} color="#10B981" />
            <Text style={styles.sectionHeaderText}>Correlations</Text>
          </View>
          {survey.correlations.map(
            (correlation: Correlation, index: number) => (
              <View key={index} style={styles.correlationCard}>
                <Text style={styles.correlationDescription}>
                  {correlation.description}
                </Text>
                <View style={styles.evidenceBox}>
                  <Ionicons name="checkmark-circle" size={16} color="#10B981" />
                  <Text style={styles.evidenceText}>
                    {correlation.evidence}
                  </Text>
                </View>
              </View>
            )
          )}
        </View>
      )}

      {/* Caveats */}
      {survey.caveats && survey.caveats.length > 0 && (
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Ionicons name="warning" size={20} color="#EF4444" />
            <Text style={styles.sectionHeaderText}>Caveats</Text>
          </View>
          <View style={styles.caveatsBox}>
            {survey.caveats.map((caveat: string, index: number) => (
              <View key={index} style={styles.caveatItem}>
                <Ionicons name="alert-circle" size={16} color="#EF4444" />
                <Text style={styles.caveatText}>{caveat}</Text>
              </View>
            ))}
          </View>
        </View>
      )}

      {/* Empty State */}
      {(!survey.findings || survey.findings.length === 0) &&
        (!survey.insights || survey.insights.length === 0) &&
        (!survey.correlations || survey.correlations.length === 0) && (
          <View style={styles.emptyState}>
            <Ionicons
              name="information-circle-outline"
              size={32}
              color="#9CA3AF"
            />
            <Text style={styles.emptyText}>No detailed insights available</Text>
          </View>
        )}
    </View>
  );
};

interface StatCardProps {
  icon: string;
  label: string;
  value: number;
  color: string;
}

const StatCard: React.FC<StatCardProps> = ({ icon, label, value, color }) => {
  return (
    <View style={styles.statCard}>
      <View
        style={[styles.statIconContainer, { backgroundColor: `${color}15` }]}
      >
        <Ionicons name={icon as any} size={24} color={color} />
      </View>
      <Text style={styles.statValue}>{value}</Text>
      <Text style={styles.statLabel}>{label}</Text>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F9FAFB",
  },
  centerContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 14,
    color: "#6B7280",
  },
  errorText: {
    marginTop: 16,
    fontSize: 14,
    color: "#EF4444",
    textAlign: "center",
  },
  button: {
    marginTop: 16,
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: "#8B5CF6",
    borderRadius: 8,
  },
  buttonText: {
    color: "#FFFFFF",
    fontWeight: "600",
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 24,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 24,
  },
  backButton: {
    marginRight: 16,
  },
  headerTextContainer: {
    flex: 1,
  },
  shareButton: {
    marginLeft: 16,
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 14,
    color: "#6B7280",
  },
  successBadge: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ECFDF5",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    marginBottom: 24,
    gap: 8,
  },
  successText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#065F46",
  },
  statsGrid: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 24,
  },
  statCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  statIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  statValue: {
    fontSize: 24,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: "#6B7280",
    textAlign: "center",
  },
  qualityCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  confidenceRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  confidenceLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#374151",
  },
  confidenceBadge: {
    backgroundColor: "#ECFDF5",
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 12,
  },
  confidenceValue: {
    fontSize: 16,
    fontWeight: "700",
    color: "#065F46",
  },
  qualityText: {
    fontSize: 14,
    color: "#374151",
    lineHeight: 20,
    marginBottom: 12,
  },
  notesSection: {
    marginTop: 8,
  },
  noteItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 8,
    gap: 8,
  },
  noteText: {
    flex: 1,
    fontSize: 13,
    color: "#6B7280",
    lineHeight: 18,
  },
  overviewCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    gap: 12,
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#111827",
  },
  overviewText: {
    fontSize: 16,
    color: "#374151",
    lineHeight: 24,
  },
  surveysSection: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 16,
  },
  surveyCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  surveyHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
    flexWrap: "wrap",
    gap: 8,
  },
  surveyTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: "700",
    color: "#111827",
  },
  responseBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F5F3FF",
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 12,
    gap: 4,
  },
  responseText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#8B5CF6",
  },
  section: {
    marginBottom: 20,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    gap: 8,
  },
  sectionHeaderText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#111827",
  },
  findingCard: {
    backgroundColor: "#FFF7ED",
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
  },
  findingTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: "#92400E",
    marginBottom: 6,
  },
  findingDescription: {
    fontSize: 14,
    color: "#92400E",
    lineHeight: 20,
  },
  insightCard: {
    backgroundColor: "#F9FAFB",
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
  },
  themeChip: {
    alignSelf: "flex-start",
    backgroundColor: "#EFF6FF",
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 12,
    marginBottom: 8,
  },
  themeText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#1E40AF",
  },
  insightTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: "#111827",
    marginBottom: 6,
  },
  insightDescription: {
    fontSize: 14,
    color: "#374151",
    lineHeight: 20,
  },
  examplesSection: {
    marginTop: 10,
  },
  examplesLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#6B7280",
    marginBottom: 6,
  },
  exampleItem: {
    flexDirection: "row",
    marginBottom: 4,
    gap: 8,
  },
  exampleBullet: {
    fontSize: 14,
    color: "#8B5CF6",
    fontWeight: "700",
  },
  exampleText: {
    flex: 1,
    fontSize: 13,
    color: "#374151",
    lineHeight: 18,
  },
  correlationCard: {
    backgroundColor: "#ECFDF5",
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
  },
  correlationDescription: {
    fontSize: 14,
    color: "#065F46",
    lineHeight: 20,
    marginBottom: 8,
  },
  evidenceBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
  },
  evidenceText: {
    flex: 1,
    fontSize: 13,
    color: "#047857",
    lineHeight: 18,
  },
  caveatsBox: {
    backgroundColor: "#FEF2F2",
    borderRadius: 12,
    padding: 14,
  },
  caveatItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 8,
    gap: 8,
  },
  caveatText: {
    flex: 1,
    fontSize: 13,
    color: "#991B1B",
    lineHeight: 18,
  },
  emptyState: {
    alignItems: "center",
    paddingVertical: 32,
  },
  emptyText: {
    marginTop: 12,
    fontSize: 14,
    color: "#6B7280",
    textAlign: "center",
  },
});
